
import RPi.GPIO as GPIO
import time
import sys

GPIO.setmode(GPIO.BCM)
#GPIO定義
motor1DIR = 6
motor2DIR = 5
motor3DIR = 26
motor4DIR = 27
motor1PWM = 4
motor2PWM = 18
motor3PWM = 13
motor4PWM = 12
#周波数
Frequencys = 50
#duty比
duty = 30
duty1 = 22
duty2 = 30
duty4 = 60
duty5 = 60
duty6 = 70
duty7 = 80
duty8 = 90
duty9 = 100
#GPIo set
GPIO.setwarnings(False)
GPIO.setup(motor1DIR,GPIO.OUT)
GPIO.setup(motor2DIR,GPIO.OUT)
GPIO.setup(motor3DIR,GPIO.OUT)
GPIO.setup(motor4DIR,GPIO.OUT)
GPIO.setup(motor1PWM,GPIO.OUT)
GPIO.setup(motor2PWM,GPIO.OUT)
GPIO.setup(motor3PWM,GPIO.OUT)
GPIO.setup(motor4PWM,GPIO.OUT)
#PWMset
p1 = GPIO.PWM(motor1PWM,Frequencys)
p2 = GPIO.PWM(motor2PWM,Frequencys)
p3 = GPIO.PWM(motor3PWM,Frequencys)
p4 = GPIO.PWM(motor4PWM,Frequencys)
#start
p1.start(0)
p2.start(0)
p3.start(0)
p4.start(0)
#モータ用のプログラム　18ヵ所　1~6までが一番下(右から一を配置)7~12までが２段目 13~18までが三段目　以下同
def type1 ():
    GPIO.output(motor1DIR,GPIO.LOW)
    GPIO.output(motor3DIR,GPIO.LOW)
    p3.ChangeDutyCycle(duty2)
    p1.ChangeDutyCycle(duty4)
    time.sleep(20)
    p1.ChangeDutyCycle(0)
    p3.ChangeDutyCycle(0)
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.HIGH)
    time.sleep(10)
    p4.ChangeDutyCycle(0)
    GPIO.output(motor2DIR,GPIO.HIGH)
    p2.ChangeDutyCycle(duty)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)
#帰り
    p2.ChangeDutyCycle(duty)
    GPIO.output(motor2DIR,GPIO.LOW)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)
    GPIO.output(motor1DIR,GPIO.HIGH)
    GPIO.output(motor3DIR,GPIO.HIGH)
    p3.ChangeDutyCycle(duty2)
    p1.ChangeDutyCycle(duty4)
    time.sleep(20)
    p1.ChangeDutyCycle(0)
    p3.ChangeDutyCycle(0)
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.LOW)
    time.sleep(10)
def type2 ():
    GPIO.output(motor1DIR,GPIO.LOW)
    GPIO.output(motor3DIR,GPIO.LOW)
    p3.ChangeDutyCycle(duty2)
    p1.ChangeDutyCycle(duty4)
    time.sleep(20)
    p1.ChangeDutyCycle(0)
    p3.ChangeDutyCycle(0)
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.HIGH)
    time.sleep(5)
    p4.ChangeDutyCycle(0)
    GPIO.output(motor2DIR,GPIO.HIGH)
    p2.ChangeDutyCycle(duty)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)
#帰えり
    p2.ChangeDutyCycle(duty)
    GPIO.output(motor2DIR,GPIO.LOW)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)
    GPIO.output(motor1DIR,GPIO.HIGH)
    GPIO.output(motor3DIR,GPIO.HIGH)
    p3.ChangeDutyCycle(duty2)
    p1.ChangeDutyCycle(duty4)
    time.sleep(20)
    p1.ChangeDutyCycle(0)
    p3.ChangeDutyCycle(0)
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.LOW)
    time.sleep(5)
def type3 ():
    GPIO.output(motor1DIR,GPIO.LOW)
    GPIO.output(motor3DIR,GPIO.LOW)
    p3.ChangeDutyCycle(duty2)
    p1.ChangeDutyCycle(duty4)
    time.sleep(20)
    p1.ChangeDutyCycle(0)
    p3.ChangeDutyCycle(0)
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.LOW)
    time.sleep(5)
    p4.ChangeDutyCycle(0)
    GPIO.output(motor2DIR,GPIO.HIGH)
    p2.ChangeDutyCycle(duty)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)
#
    p2.ChangeDutyCycle(duty)
    GPIO.output(motor2DIR,GPIO.LOW)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)
    GPIO.output(motor1DIR,GPIO.HIGH)
    GPIO.output(motor3DIR,GPIO.HIGH)
    p3.ChangeDutyCycle(duty2)
    p1.ChangeDutyCycle(duty4)
    time.sleep(20)
    p1.ChangeDutyCycle(0)
    p3.ChangeDutyCycle(0)
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.HIGH)
    time.sleep(5)
def type4 ():
    GPIO.output(motor1DIR,GPIO.LOW)
    GPIO.output(motor3DIR,GPIO.LOW)
    p3.ChangeDutyCycle(duty2)
    p1.ChangeDutyCycle(duty4)
    time.sleep(20)
    p1.ChangeDutyCycle(0)
    p3.ChangeDutyCycle(0)
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.LOW)
    time.sleep(10)
    p4.ChangeDutyCycle(0)
    GPIO.output(motor2DIR,GPIO.HIGH)
    p2.ChangeDutyCycle(duty)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)

    p2.ChangeDutyCycle(duty)
    GPIO.output(motor2DIR,GPIO.LOW)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)
    GPIO.output(motor1DIR,GPIO.HIGH)
    GPIO.output(motor3DIR,GPIO.HIGH)
    p3.ChangeDutyCycle(duty2)
    p1.ChangeDutyCycle(duty4)
    time.sleep(20)
    p1.ChangeDutyCycle(0)
    p3.ChangeDutyCycle(0)
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.HIGH)
    time.sleep(10)
def type5 ():
    GPIO.output(motor1DIR,GPIO.LOW)
    GPIO.output(motor3DIR,GPIO.LOW)
    p3.ChangeDutyCycle(duty2)
    p1.ChangeDutyCycle(duty4)
    time.sleep(10)
    p1.ChangeDutyCycle(0)
    p3.ChangeDutyCycle(0)
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.HIGH)
    time.sleep(10)
    p4.ChangeDutyCycle(0)
    GPIO.output(motor2DIR,GPIO.HIGH)
    p2.ChangeDutyCycle(duty)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)

    p2.ChangeDutyCycle(duty)
    GPIO.output(motor2DIR,GPIO.LOW)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)
    GPIO.output(motor1DIR,GPIO.HIGH)
    GPIO.output(motor3DIR,GPIO.HIGH)
    p3.ChangeDutyCycle(duty2)
    p1.ChangeDutyCycle(duty4)
    time.sleep(10)
    p1.ChangeDutyCycle(0)
    p3.ChangeDutyCycle(0)
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.LOW)
    time.sleep(10)
def type6 ():
    GPIO.output(motor1DIR,GPIO.LOW)
    GPIO.output(motor3DIR,GPIO.LOW)
    p3.ChangeDutyCycle(duty2)
    p1.ChangeDutyCycle(duty4)
    time.sleep(10)
    p1.ChangeDutyCycle(0)
    p3.ChangeDutyCycle(0)
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.HIGH)
    time.sleep(5)
    p4.ChangeDutyCycle(0)
    GPIO.output(motor2DIR,GPIO.HIGH)
    p2.ChangeDutyCycle(duty)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)

    p2.ChangeDutyCycle(duty)
    GPIO.output(motor2DIR,GPIO.LOW)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)
    GPIO.output(motor1DIR,GPIO.HIGH)
    GPIO.output(motor3DIR,GPIO.HIGH)
    p3.ChangeDutyCycle(duty2)
    p1.ChangeDutyCycle(duty4)
    time.sleep(10)
    p1.ChangeDutyCycle(0)
    p3.ChangeDutyCycle(0)
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.LOW)
    time.sleep(5)
def type7 ():
    GPIO.output(motor1DIR,GPIO.LOW)
    GPIO.output(motor3DIR,GPIO.LOW)
    p3.ChangeDutyCycle(duty2)
    p1.ChangeDutyCycle(duty4)
    time.sleep(10)
    p1.ChangeDutyCycle(0)
    p3.ChangeDutyCycle(0)
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.LOW)
    time.sleep(5)
    p4.ChangeDutyCycle(0)
    GPIO.output(motor2DIR,GPIO.HIGH)
    p2.ChangeDutyCycle(duty)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)

    p2.ChangeDutyCycle(duty)
    GPIO.output(motor2DIR,GPIO.LOW)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)
    GPIO.output(motor1DIR,GPIO.HIGH)
    GPIO.output(motor3DIR,GPIO.HIGH)
    p3.ChangeDutyCycle(duty2)
    p1.ChangeDutyCycle(duty4)
    time.sleep(10)
    p1.ChangeDutyCycle(0)
    p3.ChangeDutyCycle(0)
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.HIGH)
    time.sleep(5)
    p4.ChangeDutyCycle(0)
def type8 ():
    GPIO.output(motor1DIR,GPIO.LOW)
    GPIO.output(motor3DIR,GPIO.LOW)
    p3.ChangeDutyCycle(duty2)
    p1.ChangeDutyCycle(duty4)
    time.sleep(10)
    p1.ChangeDutyCycle(0)
    p3.ChangeDutyCycle(0)
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.LOW)
    time.sleep(10)
    p4.ChangeDutyCycle(0)
    GPIO.output(motor2DIR,GPIO.HIGH)
    p2.ChangeDutyCycle(duty)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)

    p2.ChangeDutyCycle(duty)
    GPIO.output(motor2DIR,GPIO.LOW)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)
    GPIO.output(motor1DIR,GPIO.HIGH)
    GPIO.output(motor3DIR,GPIO.HIGH)
    p3.ChangeDutyCycle(duty2)
    p1.ChangeDutyCycle(duty4)
    time.sleep(10)
    p1.ChangeDutyCycle(0)
    p3.ChangeDutyCycle(0)
    GPIO.output(motor4DIR,GPIO.HIGH)
    time.sleep(10)
    p4.ChangeDutyCycle(0)
def type9 ():
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.HIGH)
    time.sleep(10)
    p4.ChangeDutyCycle(0)
    GPIO.output(motor2DIR,GPIO.HIGH)
    p2.ChangeDutyCycle(duty)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)

    p2.ChangeDutyCycle(duty)
    GPIO.output(motor2DIR,GPIO.LOW)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.LOW)
    time.sleep(10)
    p4.ChangeDutyCycle(0)
def type10 ():
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.HIGH)
    time.sleep(5)
    p4.ChangeDutyCycle(0)
    GPIO.output(motor2DIR,GPIO.HIGH)
    p2.ChangeDutyCycle(duty)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)

    p2.ChangeDutyCycle(duty)
    GPIO.output(motor2DIR,GPIO.LOW)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.LOW)
    time.sleep(5)
    p4.ChangeDutyCycle(0)
def type11 ():
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.LOW)
    time.sleep(5)
    p4.ChangeDutyCycle(0)
    GPIO.output(motor2DIR,GPIO.HIGH)
    p2.ChangeDutyCycle(duty)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)

    p2.ChangeDutyCycle(duty)
    GPIO.output(motor2DIR,GPIO.LOW)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.HIGH)
    time.sleep(5)
    p4.ChangeDutyCycle(0)
def type12 ():
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.LOW)
    time.sleep(10)
    p4.ChangeDutyCycle(0)
    GPIO.output(motor2DIR,GPIO.HIGH)
    p2.ChangeDutyCycle(duty)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)

    p2.ChangeDutyCycle(duty)
    GPIO.output(motor2DIR,GPIO.LOW)
    time.sleep(4.3)
    p2.ChangeDutyCycle(0)
    p4.ChangeDutyCycle(duty1)
    GPIO.output(motor4DIR,GPIO.HIGH)
    time.sleep(10)
def type13 ():
    p1.ChangeDutyCycle(duty)
    GPIO.output(motor1DIR,GPIO.HIGH)

def type14 ():
    p1.ChangeDutyCycle(duty)
    GPIO.output(motor1DIR,GPIO.HIGH)

def type15 ():
    p1.ChangeDutyCycle(duty)
    GPIO.output(motor1DIR,GPIO.HIGH)

def type16 ():
    p1.ChangeDutyCycle(duty)
    GPIO.output(motor1DIR,GPIO.HIGH)

def type17 ():
    p1.ChangeDutyCycle(duty)
    GPIO.output(motor1DIR,GPIO.HIGH)

def type18 ():
    p1.ChangeDutyCycle(duty)
    GPIO.output(motor1DIR,GPIO.HIGH)

def reset ():
    p1.ChangeDutyCycle(duty)
    GPIO.output(motor1DIR,GPIO.HIGH)
    p3.ChangeDutyCycle(duty)
    GPIO.output(motor3DIR,GPIO.HIGH)
def reset2():
    p2.ChangeDutyCycle(duty)
    GPIO.output(motor2DIR,GPIO.HIGH)
def Emergencies ():
    #0のときとまる
    #dutyで動く(信号送信)
    p1.ChangeDutyCycle(0)
    p2.ChangeDutyCycle(0)
    p3.ChangeDutyCycle(0)
    p4.ChangeDutyCycle(0)
def updownstop ():
    p1.ChangeDutyCycle(0)
    p3.ChangeDutyCycle(0)
def rightleftstop():
    p2.ChangeDutyCycle(0)
